name    'yguenane-augeas'
version '0.1.0'
source 'https://github.com/Spredzy/puppet-augeas'
author 'Yanis Guenane'
license 'Apache License, Version 2.0'
summary 'Up to date Augeas core version'
description 'A puppet module that installs augeas latest version'
project_page 'https://github.com/Spredzy/puppet-augeas'
